"""empty message

Revision ID: 07bb7e39d75e
Revises: b61e7cd71de7
Create Date: 2023-04-12 17:17:51.166908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bb7e39d75e'
down_revision = 'b61e7cd71de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'address')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
