"""empty message

Revision ID: 174e842f07f3
Revises: 325f8cfbc0a0
Create Date: 2023-04-17 01:50:40.008733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174e842f07f3'
down_revision = '325f8cfbc0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
