"""empty message

Revision ID: 325f8cfbc0a0
Revises: ab0448548bcc
Create Date: 2023-04-16 01:30:52.575983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325f8cfbc0a0'
down_revision = 'ab0448548bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
