"""empty message

Revision ID: 9936e615d347
Revises: cbb9c5c696fd
Create Date: 2023-04-28 01:27:35.354740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9936e615d347'
down_revision = 'cbb9c5c696fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_products', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_products'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_products')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
